/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Javaticket_harlenlopez1;

import static Javaticket_harlenlopez1.Crear_Usuario.cantidadeusuarios;
import static Javaticket_harlenlopez1.Crear_Usuario.users;
import static Javaticket_harlenlopez1.Crear_Usuario.llamar;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class Borrar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Borrar_Usuario
     */
    public Borrar_Usuario() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    public static int edadCrear=0;
    public static boolean puedeAvanzar=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordTextbox = new javax.swing.JTextField();
        UsuarioTextbox = new javax.swing.JTextField();
        backgroundLabel = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        Crear_usuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PasswordTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 345, -1));
        getContentPane().add(UsuarioTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 345, -1));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrar_usuario_background.png"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 367));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 150, 50));

        Crear_usuario.setText("Borrar Usuario");
        Crear_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Crear_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 200, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        Administracion_de_usuarios pasar=new Administracion_de_usuarios();
        pasar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void Crear_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_usuarioActionPerformed
        // TODO add your handling code here:
        String usuarioCrear=UsuarioTextbox.getText();
        String contraseñaCrear=PasswordTextbox.getText();
        boolean noExiste=false;
        if(usuarioCrear.isEmpty()||contraseñaCrear.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor, llenar todos los campos.");
        }else{
            for(int indice=0;indice<users.size();indice++){
                if(users.get(indice)!=null){
                    if(users.get(indice).getUser().equals(usuarioCrear)){
                        if(users.get(indice).getPassword().equals(contraseñaCrear)){
                            if(users.get(indice).getTipo()==0){
                                noExiste=true;
                            }else{
                                Usuarios borrarUsuario = new Usuarios("","","",0,0);
                                users.set(indice,borrarUsuario);
                                JOptionPane.showMessageDialog(null, "Ha borrado exitosamente su cuenta.");
                                cantidadeusuarios--;
                                noExiste=false;
                                Administracion_de_usuarios pasar=new Administracion_de_usuarios();
                                pasar.setVisible(true);
                                this.setVisible(false);
                                break;
                            }
                        }else{
                            noExiste=true;
                        }
                    }else{
                        noExiste=true;
                    }
                }
            }
            if(noExiste==true){
                JOptionPane.showMessageDialog(null, "Usuario no existe.");
            }
        }
    }//GEN-LAST:event_Crear_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrar_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crear_usuario;
    private javax.swing.JTextField PasswordTextbox;
    private javax.swing.JTextField UsuarioTextbox;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton cancelar;
    // End of variables declaration//GEN-END:variables
}
