/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Javaticket_harlenlopez1;

import static Javaticket_harlenlopez1.Crear_Usuario.users;
import static Javaticket_harlenlopez1.Crear_Evento.eventos;
import static Javaticket_harlenlopez1.MAIN_Login.pos;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    public static Date fecha,fechaInicial,fechaFinal;
    public static ArrayList algo=new ArrayList<>();
    public static DefaultListModel modelo=new DefaultListModel();
    public static Date fechaprueba;
    public static String tipo,totalDeportivo,totalMusical,totalReligioso;
    public static reportesClase llamar=new reportesClase();
    public static double montoTotal;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloTextBox = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        cantidadDeportes = new javax.swing.JLabel();
        cantidadReligiosos = new javax.swing.JLabel();
        cantidadMusicales = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Ingresar = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        fechafinal = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        fechainicial = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        PerfilUsuario = new javax.swing.JButton();
        Ingreso = new javax.swing.JButton();
        eventosCancelados = new javax.swing.JButton();
        eventosFuturos = new javax.swing.JButton();
        eventosRealizados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(TituloTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 300, 10));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 690, 140));

        cantidadDeportes.setForeground(new java.awt.Color(0, 0, 0));
        cantidadDeportes.setText("0");
        getContentPane().add(cantidadDeportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        cantidadReligiosos.setForeground(new java.awt.Color(0, 0, 0));
        cantidadReligiosos.setText("0");
        getContentPane().add(cantidadReligiosos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        cantidadMusicales.setForeground(new java.awt.Color(0, 0, 0));
        cantidadMusicales.setText("0");
        getContentPane().add(cantidadMusicales, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ingresar.setBackground(new java.awt.Color(255, 255, 255));
        Ingresar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(0, 0, 0));
        Ingresar.setText("Ingresar fechas");
        Ingresar.setBorder(new javax.swing.border.MatteBorder(null));
        Ingresar.setVisible(false);
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 730, 150, 50));

        jDateChooser2.setVisible(false);
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 740, 120, -1));

        fechafinal.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        fechafinal.setForeground(new java.awt.Color(0, 0, 0));
        fechafinal.setText("Fecha Final:");
        fechafinal.setVisible(false);
        jPanel1.add(fechafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 740, 100, -1));

        jDateChooser1.setVisible(false);
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 740, 120, -1));

        fechainicial.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        fechainicial.setForeground(new java.awt.Color(0, 0, 0));
        fechainicial.setText("Fecha Inicial:");
        fechainicial.setVisible(false);
        jPanel1.add(fechainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, 100, -1));

        regresar.setBackground(new java.awt.Color(255, 255, 255));
        regresar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        regresar.setForeground(new java.awt.Color(0, 0, 0));
        regresar.setText("Regresar a Menú Principal");
        regresar.setBorder(new javax.swing.border.MatteBorder(null));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 230, 60));

        PerfilUsuario.setBackground(new java.awt.Color(255, 255, 255));
        PerfilUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        PerfilUsuario.setForeground(new java.awt.Color(0, 0, 0));
        PerfilUsuario.setText("Ver Perfil de usuario");
        PerfilUsuario.setBorder(new javax.swing.border.MatteBorder(null));
        PerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 180, 60));

        Ingreso.setBackground(new java.awt.Color(255, 255, 255));
        Ingreso.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Ingreso.setForeground(new java.awt.Color(0, 0, 0));
        Ingreso.setText("Ingreso generado por fecha");
        Ingreso.setBorder(new javax.swing.border.MatteBorder(null));
        Ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoActionPerformed(evt);
            }
        });
        jPanel1.add(Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 240, 60));

        eventosCancelados.setBackground(new java.awt.Color(255, 255, 255));
        eventosCancelados.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        eventosCancelados.setForeground(new java.awt.Color(0, 0, 0));
        eventosCancelados.setText("Listar eventos cancelados");
        eventosCancelados.setBorder(new javax.swing.border.MatteBorder(null));
        eventosCancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosCanceladosActionPerformed(evt);
            }
        });
        jPanel1.add(eventosCancelados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 220, 60));

        eventosFuturos.setBackground(new java.awt.Color(255, 255, 255));
        eventosFuturos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        eventosFuturos.setForeground(new java.awt.Color(0, 0, 0));
        eventosFuturos.setText("Listar eventos futuros");
        eventosFuturos.setBorder(new javax.swing.border.MatteBorder(null));
        eventosFuturos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosFuturosActionPerformed(evt);
            }
        });
        jPanel1.add(eventosFuturos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 190, 60));

        eventosRealizados.setBackground(new java.awt.Color(255, 255, 255));
        eventosRealizados.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        eventosRealizados.setForeground(new java.awt.Color(0, 0, 0));
        eventosRealizados.setText("Listar eventos realizados");
        eventosRealizados.setBorder(new javax.swing.border.MatteBorder(null));
        eventosRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosRealizadosActionPerformed(evt);
            }
        });
        jPanel1.add(eventosRealizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 210, 60));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 440, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventosRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosRealizadosActionPerformed
        // TODO add your handling code here:
        jDateChooser1.setVisible(false);
        jDateChooser2.setVisible(false);
        fechainicial.setVisible(false);
        fechafinal.setVisible(false);
        Ingresar.setVisible(false);
        TituloTextBox.setText("Lista de eventos realizados:");
        modelo.clear();
        montoTotal=0;
        llamar.cantiadadDeportivo=0;
        llamar.cantiadadMusical=0;
        llamar.cantiadadReligioso=0;
        llamar.listaDeEventosRealizados(0);
        modelo.addElement("Monto Total de eventos: "+montoTotal);
        jList1.setModel(modelo);
        totalDeportivo=String.valueOf(llamar.cantiadadDeportivo);
        cantidadDeportes.setText(totalDeportivo);
        totalMusical=String.valueOf(llamar.cantiadadMusical);
        cantidadMusicales.setText(totalMusical);
        totalReligioso=String.valueOf(llamar.cantiadadReligioso);
        cantidadReligiosos.setText(totalReligioso);
        
        //jPanel2 = new Grafica(Crear_Evento.dineroDeportes, Crear_Evento.dineroReligioso, Crear_Evento.dineroMusical);
        javax.swing.JPanel xd = new Grafica(Crear_Evento.dineroDeportes, Crear_Evento.dineroReligioso, Crear_Evento.dineroMusical);
        xd.setLocation(0,0);
        jPanel2.add(xd);
        jPanel2.repaint();
    }//GEN-LAST:event_eventosRealizadosActionPerformed

    private void eventosFuturosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosFuturosActionPerformed
        // TODO add your handling code here:
        jDateChooser1.setVisible(false);
        jDateChooser2.setVisible(false);
        fechainicial.setVisible(false);
        fechafinal.setVisible(false);
        Ingresar.setVisible(false);
        TituloTextBox.setText("Lista de eventos futuros:");
        modelo.clear();
        montoTotal=0;
        llamar.cantiadadDeportivo=0;
        llamar.cantiadadMusical=0;
        llamar.cantiadadReligioso=0;
        llamar.listaDeEventosFuturos(0);
        modelo.addElement("Monto Total de eventos: "+montoTotal);
        jList1.setModel(modelo);
        totalDeportivo=String.valueOf(llamar.cantiadadDeportivo);
        cantidadDeportes.setText(totalDeportivo);
        totalMusical=String.valueOf(llamar.cantiadadMusical);
        cantidadMusicales.setText(totalMusical);
        totalReligioso=String.valueOf(llamar.cantiadadReligioso);
        cantidadReligiosos.setText(totalReligioso);
    }//GEN-LAST:event_eventosFuturosActionPerformed

    private void eventosCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosCanceladosActionPerformed
        // TODO add your handling code here:
        jDateChooser1.setVisible(false);
        jDateChooser2.setVisible(false);
        fechainicial.setVisible(false);
        fechafinal.setVisible(false);
        Ingresar.setVisible(false);
        TituloTextBox.setText("Lista de eventos cancelados:");
        modelo.clear();
        montoTotal=0;
        llamar.cantiadadDeportivo=0;
        llamar.cantiadadMusical=0;
        llamar.cantiadadReligioso=0;
        llamar.listaDeEventosCancelados(0);
        totalDeportivo=String.valueOf(llamar.cantiadadDeportivo);
        cantidadDeportes.setText(totalDeportivo);
        totalMusical=String.valueOf(llamar.cantiadadMusical);
        cantidadMusicales.setText(totalMusical);
        totalReligioso=String.valueOf(llamar.cantiadadReligioso);
        cantidadReligiosos.setText(totalReligioso);
    }//GEN-LAST:event_eventosCanceladosActionPerformed

    private void PerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilUsuarioActionPerformed
        // TODO add your handling code here:
        jDateChooser1.setVisible(false);
        jDateChooser2.setVisible(false);
        fechainicial.setVisible(false);
        fechafinal.setVisible(false);
        Ingresar.setVisible(false);
        TituloTextBox.setText("Perfil de usuario:");
        modelo.clear();
        if(users.get(pos).getTipo()==1){
            tipo="Administrativo";
        }else if(users.get(pos).getTipo()==2){
            tipo="Contenido";
        }else{
            tipo="Limitado";
        }
        modelo.addElement("Nombre Completo: "+users.get(pos).getName()+", Usuario: "+users.get(pos).getUser()+
                "\n "+"Contraseña: "+users.get(pos).getPassword()+", Edad: "+users.get(pos).getEdad()+", Tipo: "+tipo);
        jList1.setModel(modelo);
        llamar.cantiadadDeportivo=0;
        llamar.cantiadadMusical=0;
        llamar.cantiadadReligioso=0;
        llamar.verPerfilDeUsuario(0);
        totalDeportivo=String.valueOf(llamar.cantiadadDeportivo);
        cantidadDeportes.setText(totalDeportivo);
        totalMusical=String.valueOf(llamar.cantiadadMusical);
        cantidadMusicales.setText(totalMusical);
        totalReligioso=String.valueOf(llamar.cantiadadReligioso);
        cantidadReligiosos.setText(totalReligioso);
    }//GEN-LAST:event_PerfilUsuarioActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        modelo.clear();
        Sistema pasar=new Sistema();
        pasar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void IngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoActionPerformed
        // TODO add your handling code here:
        TituloTextBox.setText("Ingreso generado por fecha:");
        jDateChooser1.setVisible(true);
        jDateChooser2.setVisible(true);
        fechainicial.setVisible(true);
        fechafinal.setVisible(true);
        Ingresar.setVisible(true);
    }//GEN-LAST:event_IngresoActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        // TODO add your handling code here:
        montoTotal=0;
        fechaInicial=jDateChooser1.getDate();
        fechaFinal=jDateChooser2.getDate();
        if(fechaInicial!=null||fechaFinal!=null){
            if(fechaInicial.before(fechaFinal)){
                modelo.clear();
                llamar.ingresoGeneradoPorFecha(0);
                modelo.addElement("Monto Total de Ingreso Generado por Fecha: "+montoTotal);
                jList1.setModel(modelo);
                jDateChooser1.setVisible(false);
                jDateChooser2.setVisible(false);
                fechainicial.setVisible(false);
                fechafinal.setVisible(false);
                Ingresar.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Asegurese de poner las fechas correctamente");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Asegurese de llenar todas las fechas, porfavor.");
        }
    }//GEN-LAST:event_IngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton Ingreso;
    private javax.swing.JButton PerfilUsuario;
    private javax.swing.JLabel TituloTextBox;
    public static javax.swing.JLabel cantidadDeportes;
    public static javax.swing.JLabel cantidadMusicales;
    public static javax.swing.JLabel cantidadReligiosos;
    private javax.swing.JButton eventosCancelados;
    private javax.swing.JButton eventosFuturos;
    private javax.swing.JButton eventosRealizados;
    public static javax.swing.JLabel fechafinal;
    public static javax.swing.JLabel fechainicial;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    public static javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
